org: krishmehra
app: sentiment-pulse
useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies


  
service: sentiment-backend
provider:
  name: aws
  runtime: nodejs20.x
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    IBM_API_KEY: ${env:IBM_SERVICE_URL}
    IBM_SERVICE_URL: ${env:IBM_API_KEY}

functions:
  api:
    handler: handler.index
    events:
      - http: any {proxy+}

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - README.md
    - .env
