name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          IBM_API_KEY: ${{ secrets.IBM_API_KEY }}
          IBM_SERVICE_URL: ${{ secrets.IBM_SERVICE_URL }}
          PORT: ${{ secrets.PORT }}
        run: npm test

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          APPLICATION_NAME: 'pulse-node-backend'
          ENVIRONMENT_NAME: 'backend-dev'
        run: |
          npm install -g awsebcli
          eb init -p node.js $APPLICATION_NAME --region $AWS_REGION --interactive false
          echo "MONGODB_URI=$MONGODB_URI" >> .elasticbeanstalk/.env
          echo "IBM_API_KEY=$IBM_API_KEY" >> .elasticbeanstalk/.env
          echo "IBM_SERVICE_URL=$IBM_SERVICE_URL" >> .elasticbeanstalk/.env
          echo "PORT=$PORT" >> .elasticbeanstalk/.env
          eb use $ENVIRONMENT_NAME
          eb deploy
